"""add_health_data_if_and_new_anomaly_types

Revision ID: 4360d097bff0
Revises: 7f39d0510ecc
Create Date: 2026-04-20 12:36:57.819943
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4360d097bff0'
down_revision: Union[str, None] = '7f39d0510ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_data_if',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('if_id', sa.Integer(), nullable=False),
    sa.Column('data_base', sa.Date(), nullable=False),
    sa.Column('indice_basileia', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('patrimonio_liquido', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('indice_liquidez', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ativos_liquidos', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ativo_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('depositos_totais', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('inadimplencia', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fonte', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['if_id'], ['instituicoes_financeiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_data_if', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_data_if_data_base'), ['data_base'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_data_if_if_id'), ['if_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_data_if', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_data_if_if_id'))
        batch_op.drop_index(batch_op.f('ix_health_data_if_data_base'))

    op.drop_table('health_data_if')
    # ### end Alembic commands ###
