"""add_phase4_models

Revision ID: 81a87cdde4b2
Revises: 9e4fdd7f0113
Create Date: 2026-01-24 09:59:50.319649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a87cdde4b2'
down_revision: Union[str, Sequence[str], None] = '9e4fdd7f0113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precos_secundarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('if_id', sa.Integer(), nullable=True),
    sa.Column('codigo_titulo', sa.String(length=50), nullable=False),
    sa.Column('emissor_cnpj', sa.String(length=18), nullable=False),
    sa.Column('emissor_nome', sa.String(length=255), nullable=False),
    sa.Column('tipo_titulo', sa.Enum('CDB', 'LCI', 'LCA', 'LC', 'DEBENTURE', 'CRI', 'CRA', 'OUTROS', name='tipotitulosecundario'), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('pu_abertura', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('pu_fechamento', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('pu_minimo', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('pu_maximo', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('pu_medio', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('quantidade_negocios', sa.Integer(), nullable=False),
    sa.Column('quantidade_titulos', sa.Integer(), nullable=False),
    sa.Column('valor_financeiro', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('taxa_minima', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('taxa_maxima', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('taxa_media', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('variacao_dia', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['if_id'], ['instituicoes_financeiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('precos_secundarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_precos_secundarios_codigo_titulo'), ['codigo_titulo'], unique=False)
        batch_op.create_index(batch_op.f('ix_precos_secundarios_data_referencia'), ['data_referencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_precos_secundarios_emissor_cnpj'), ['emissor_cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_precos_secundarios_if_id'), ['if_id'], unique=False)

    op.create_table('processos_regulatorios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('if_id', sa.Integer(), nullable=True),
    sa.Column('numero_processo', sa.String(length=50), nullable=False),
    sa.Column('cnpj_envolvido', sa.String(length=18), nullable=True),
    sa.Column('nome_envolvido', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('ADMINISTRATIVO', 'SANCIONADOR', 'CONSULTA', 'DENUNCIA', 'FISCALIZACAO', 'OUTRO', name='tipoprocessobc'), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'SUSPENSO', 'ARQUIVADO', 'CONCLUIDO', name='statusprocesso'), nullable=False),
    sa.Column('assunto', sa.Text(), nullable=True),
    sa.Column('data_abertura', sa.Date(), nullable=False),
    sa.Column('data_atualizacao', sa.Date(), nullable=True),
    sa.Column('data_conclusao', sa.Date(), nullable=True),
    sa.Column('valor_multa', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('outras_penalidades', sa.Text(), nullable=True),
    sa.Column('url_fonte', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['if_id'], ['instituicoes_financeiras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_processo')
    )
    with op.batch_alter_table('processos_regulatorios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processos_regulatorios_cnpj_envolvido'), ['cnpj_envolvido'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_regulatorios_data_abertura'), ['data_abertura'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_regulatorios_if_id'), ['if_id'], unique=False)

    op.create_table('reclamacoes_historico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('if_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.String(length=100), nullable=True),
    sa.Column('empresa_nome', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('data_coleta', sa.DateTime(), nullable=False),
    sa.Column('nota_geral', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('indice_solucao', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('indice_resposta', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_reclamacoes', sa.Integer(), nullable=False),
    sa.Column('reclamacoes_respondidas', sa.Integer(), nullable=False),
    sa.Column('reclamacoes_resolvidas', sa.Integer(), nullable=False),
    sa.Column('reclamacoes_nao_resolvidas', sa.Integer(), nullable=False),
    sa.Column('reclamacoes_30d', sa.Integer(), nullable=False),
    sa.Column('nota_30d', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('variacao_nota', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('variacao_reclamacoes', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['if_id'], ['instituicoes_financeiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reclamacoes_historico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reclamacoes_historico_cnpj'), ['cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_reclamacoes_historico_data_coleta'), ['data_coleta'], unique=False)
        batch_op.create_index(batch_op.f('ix_reclamacoes_historico_if_id'), ['if_id'], unique=False)

    op.create_table('sinais_risco_agregados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('if_id', sa.Integer(), nullable=False),
    sa.Column('score_reclame_aqui', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_processos_bc', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_mercado_secundario', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_sentimento', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_consolidado', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('nivel_risco', sa.Enum('BAIXO', 'MODERADO', 'ELEVADO', 'ALTO', 'CRITICO', name='nivelriscodb'), nullable=False),
    sa.Column('confianca', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('sinais_disponiveis', sa.Integer(), nullable=False),
    sa.Column('fatores_risco', sa.JSON(), nullable=True),
    sa.Column('recomendacoes', sa.JSON(), nullable=True),
    sa.Column('calculado_em', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['if_id'], ['instituicoes_financeiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sinais_risco_agregados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sinais_risco_agregados_calculado_em'), ['calculado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_sinais_risco_agregados_if_id'), ['if_id'], unique=False)

    op.create_table('taxas_coletadas_plataformas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('if_id', sa.Integer(), nullable=True),
    sa.Column('plataforma', sa.String(length=50), nullable=False),
    sa.Column('data_coleta', sa.DateTime(), nullable=False),
    sa.Column('emissor_cnpj', sa.String(length=18), nullable=False),
    sa.Column('emissor_nome', sa.String(length=255), nullable=False),
    sa.Column('indexador', sa.Enum('CDI', 'IPCA', 'PREFIXADO', 'SELIC', name='indexador'), nullable=False),
    sa.Column('percentual', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('taxa_adicional', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('prazo_dias', sa.Integer(), nullable=False),
    sa.Column('valor_minimo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('liquidez_diaria', sa.Boolean(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['if_id'], ['instituicoes_financeiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taxas_coletadas_plataformas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxas_coletadas_plataformas_data_coleta'), ['data_coleta'], unique=False)
        batch_op.create_index(batch_op.f('ix_taxas_coletadas_plataformas_emissor_cnpj'), ['emissor_cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_taxas_coletadas_plataformas_if_id'), ['if_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taxas_coletadas_plataformas_plataforma'), ['plataforma'], unique=False)

    with op.batch_alter_table('anomalias', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=19),
               type_=sa.Enum('SPREAD_ALTO', 'SPREAD_CRITICO', 'SALTO_BRUSCO', 'SALTO_EXTREMO', 'DIVERGENCIA', 'DIVERGENCIA_EXTREMA', 'SEASONALITY_BREAK', 'CHANGE_POINT', 'ROLLING_OUTLIER', 'CLUSTER_OUTLIER', 'ISOLATION_ANOMALY', 'PLATFORM_DISCREPANCY', 'RATE_SPIKE_CROSS_PLATFORM', 'SECONDARY_PRICE_DROP', 'SECONDARY_DAILY_DROP', 'SECONDARY_RATE_SPIKE', 'COMPLAINT_SPIKE', 'REGULATORY_PROCESS', 'NEGATIVE_SENTIMENT', 'COMPOSITE_RISK_CRITICAL', name='tipoanomalia'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomalias', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.Enum('SPREAD_ALTO', 'SPREAD_CRITICO', 'SALTO_BRUSCO', 'SALTO_EXTREMO', 'DIVERGENCIA', 'DIVERGENCIA_EXTREMA', 'SEASONALITY_BREAK', 'CHANGE_POINT', 'ROLLING_OUTLIER', 'CLUSTER_OUTLIER', 'ISOLATION_ANOMALY', 'PLATFORM_DISCREPANCY', 'RATE_SPIKE_CROSS_PLATFORM', 'SECONDARY_PRICE_DROP', 'SECONDARY_DAILY_DROP', 'SECONDARY_RATE_SPIKE', 'COMPLAINT_SPIKE', 'REGULATORY_PROCESS', 'NEGATIVE_SENTIMENT', 'COMPOSITE_RISK_CRITICAL', name='tipoanomalia'),
               type_=sa.VARCHAR(length=19),
               existing_nullable=False)

    with op.batch_alter_table('taxas_coletadas_plataformas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxas_coletadas_plataformas_plataforma'))
        batch_op.drop_index(batch_op.f('ix_taxas_coletadas_plataformas_if_id'))
        batch_op.drop_index(batch_op.f('ix_taxas_coletadas_plataformas_emissor_cnpj'))
        batch_op.drop_index(batch_op.f('ix_taxas_coletadas_plataformas_data_coleta'))

    op.drop_table('taxas_coletadas_plataformas')
    with op.batch_alter_table('sinais_risco_agregados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sinais_risco_agregados_if_id'))
        batch_op.drop_index(batch_op.f('ix_sinais_risco_agregados_calculado_em'))

    op.drop_table('sinais_risco_agregados')
    with op.batch_alter_table('reclamacoes_historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reclamacoes_historico_if_id'))
        batch_op.drop_index(batch_op.f('ix_reclamacoes_historico_data_coleta'))
        batch_op.drop_index(batch_op.f('ix_reclamacoes_historico_cnpj'))

    op.drop_table('reclamacoes_historico')
    with op.batch_alter_table('processos_regulatorios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processos_regulatorios_if_id'))
        batch_op.drop_index(batch_op.f('ix_processos_regulatorios_data_abertura'))
        batch_op.drop_index(batch_op.f('ix_processos_regulatorios_cnpj_envolvido'))

    op.drop_table('processos_regulatorios')
    with op.batch_alter_table('precos_secundarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_precos_secundarios_if_id'))
        batch_op.drop_index(batch_op.f('ix_precos_secundarios_emissor_cnpj'))
        batch_op.drop_index(batch_op.f('ix_precos_secundarios_data_referencia'))
        batch_op.drop_index(batch_op.f('ix_precos_secundarios_codigo_titulo'))

    op.drop_table('precos_secundarios')
    # ### end Alembic commands ###
