"""initial_schema

Revision ID: 9e4fdd7f0113
Revises: 
Create Date: 2026-01-22 19:20:34.459502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4fdd7f0113'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituicoes_financeiras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_reduzido', sa.String(length=100), nullable=True),
    sa.Column('segmento', sa.Enum('BANCO_COMERCIAL', 'BANCO_MULTIPLO', 'BANCO_INVESTIMENTO', 'FINANCEIRA', 'COOPERATIVA', 'OUTRO', name='segmento'), nullable=False),
    sa.Column('indice_basileia', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('indice_liquidez', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ativo_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('patrimonio_liquido', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instituicoes_financeiras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instituicoes_financeiras_cnpj'), ['cnpj'], unique=True)

    op.create_table('taxas_referencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('valor_diario', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.Column('fonte', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taxas_referencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxas_referencia_data'), ['data'], unique=False)

    op.create_table('eventos_regulatorios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('if_id', sa.Integer(), nullable=True),
    sa.Column('if_nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('INTERVENCAO', 'RAET', 'LIQUIDACAO', 'FALENCIA', 'INCORPORACAO', name='tipoevento'), nullable=False),
    sa.Column('data_evento', sa.Date(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('fonte', sa.Text(), nullable=False),
    sa.Column('fontes_adicionais', sa.JSON(), nullable=True),
    sa.Column('taxas_pre_evento', sa.JSON(), nullable=True),
    sa.Column('sinais_detectados', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['if_id'], ['instituicoes_financeiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos_regulatorios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_regulatorios_data_evento'), ['data_evento'], unique=False)

    op.create_table('taxas_cdb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('if_id', sa.Integer(), nullable=False),
    sa.Column('data_coleta', sa.DateTime(), nullable=False),
    sa.Column('indexador', sa.Enum('CDI', 'IPCA', 'PREFIXADO', 'SELIC', name='indexador'), nullable=False),
    sa.Column('percentual', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('taxa_adicional', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('prazo_dias', sa.Integer(), nullable=False),
    sa.Column('valor_minimo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('liquidez_diaria', sa.Boolean(), nullable=False),
    sa.Column('fonte', sa.String(length=50), nullable=False),
    sa.Column('url_fonte', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['if_id'], ['instituicoes_financeiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taxas_cdb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxas_cdb_data_coleta'), ['data_coleta'], unique=False)
        batch_op.create_index(batch_op.f('ix_taxas_cdb_if_id'), ['if_id'], unique=False)

    op.create_table('anomalias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('if_id', sa.Integer(), nullable=False),
    sa.Column('taxa_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('SPREAD_ALTO', 'SPREAD_CRITICO', 'SALTO_BRUSCO', 'SALTO_EXTREMO', 'DIVERGENCIA', 'DIVERGENCIA_EXTREMA', name='tipoanomalia'), nullable=False),
    sa.Column('severidade', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severidade'), nullable=False),
    sa.Column('valor_detectado', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('valor_esperado', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('desvio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.Column('detectado_em', sa.DateTime(), nullable=False),
    sa.Column('resolvido', sa.Boolean(), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(), nullable=True),
    sa.Column('notas_resolucao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['if_id'], ['instituicoes_financeiras.id'], ),
    sa.ForeignKeyConstraint(['taxa_id'], ['taxas_cdb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomalias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomalias_detectado_em'), ['detectado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomalias_if_id'), ['if_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomalias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomalias_if_id'))
        batch_op.drop_index(batch_op.f('ix_anomalias_detectado_em'))

    op.drop_table('anomalias')
    with op.batch_alter_table('taxas_cdb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxas_cdb_if_id'))
        batch_op.drop_index(batch_op.f('ix_taxas_cdb_data_coleta'))

    op.drop_table('taxas_cdb')
    with op.batch_alter_table('eventos_regulatorios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_regulatorios_data_evento'))

    op.drop_table('eventos_regulatorios')
    with op.batch_alter_table('taxas_referencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxas_referencia_data'))

    op.drop_table('taxas_referencia')
    with op.batch_alter_table('instituicoes_financeiras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instituicoes_financeiras_cnpj'))

    op.drop_table('instituicoes_financeiras')
    # ### end Alembic commands ###
